<?php

/**
 * @file
 * Contains di_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_demo module.
    case 'help.page.di_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dependency Injection Sample Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function di_demo_theme() {
  return [
    'di_demo' => [
      'render element' => 'children',
    ],
  ];
}
